using System.Text.Json.Serialization;

namespace Vera.Summarize
{
    /// <summary>
    /// Represents the response from the Deepgram API.
    /// </summary>
    public class DeepgramResponse
    {
        /// <summary>
        /// Gets or sets the results of the Deepgram API response.
        /// </summary>
        /// <value>
        /// An instance of <see cref="DeepgramResults"/> containing the API response results.
        /// </value>
        [JsonPropertyName("results")]
        public DeepgramResults? Results { get; set; }
    }

    /// <summary>
    /// Represents the results section of the Deepgram API response.
    /// </summary>
    public class DeepgramResults
    {
        /// <summary>
        /// Gets or sets the summary of the Deepgram API results.
        /// </summary>
        /// <value>
        /// An instance of <see cref="DeepgramSummary"/> containing the summarized results.
        /// </value>
        [JsonPropertyName("summary")]
        public DeepgramSummary? Summary { get; set; }
    }

    /// <summary>
    /// Represents the summary section of the Deepgram API results.
    /// </summary>
    public class DeepgramSummary
    {
        /// <summary>
        /// Gets or sets the summarized text from the Deepgram API.
        /// </summary>
        /// <value>
        /// A string containing the summarized text generated by the Deepgram API.
        /// </value>
        [JsonPropertyName("text")]
        public string? Text { get; set; }
    }

    /// <summary>
    /// Represents the response from the Edenai API.
    /// </summary>
    public class EdenaiResponse
    {
        /// <summary>
        /// Gets or sets the result of the Edenai API response.
        /// </summary>
        /// <value>
        /// A string containing the summarized text generated by the Edenai API.
        /// </value>
        [JsonPropertyName("result")]
        public string? Result { get; set; }

        /// <summary>
        /// Gets or sets the cost associated with the Edenai API request.
        /// </summary>
        /// <value>
        /// A decimal value representing the cost of the API request.
        /// </value>
        [JsonPropertyName("cost")]
        public decimal Cost { get; set; }

        /// <summary>
        /// Gets or sets the status of the Edenai API response.
        /// </summary>
        /// <value>
        /// A string indicating the status of the API response (e.g., "success" or "error").
        /// </value>
        [JsonPropertyName("status")]
        public string? Status { get; set; }
    }

    /// <summary>
    /// Represents the components of an Edenai API request.
    /// </summary>
    public class EdenaiComponents
    {
        /// <summary>
        /// Gets or sets the text to be summarized.
        /// </summary>
        /// <value>
        /// A string containing the input text to be summarized by the Edenai API.
        /// </value>
        public string? Text { get; set; }

        /// <summary>
        /// Gets or sets the providers to be used for summarization.
        /// </summary>
        /// <value>
        /// A string specifying the providers to be used for the summarization task.
        /// </value>
        public string? Providers { get; set; }

        /// <summary>
        /// Gets or sets the language of the text to be summarized.
        /// </summary>
        /// <value>
        /// A string representing the language code of the input text.
        /// </value>
        public string? Language { get; set; }

        /// <summary>
        /// Gets or sets the number of sentences in the output summary.
        /// </summary>
        /// <value>
        /// An integer specifying the desired number of sentences in the generated summary.
        /// </value>
        public int OutputSentences { get; set; }
    }
}
